input = ['młody', 'powolny', 'wspaniały', 'niezwykły', 'główny', 'ładny', 'pewny', 'słodki', 'tradycyjny', 'cały',
         'głęboki', 'męczący', 'prawdziwy', 'powszechny', 'martwy', 'niski', 'ciepły', 'słaby', 'szczupły',
         'niebezpieczny', 'zgniły', 'pomarańczowy', 'żywy', 'potężny', 'ostateczny', 'wielki', 'męczący', 'gorzki',
         'bezpłatny', 'gotowy', 'odważny', 'kiepski', 'czarny', 'lekki', 'ciasny', 'następny', 'kwadratowy', 'głodny',
         'błędny', 'zmęczony', 'uważny', 'zwykły', 'zielony', 'jasny', 'wolny', 'czarujący', 'konieczny', 'wrażliwy',
         'kruchy', 'ciężki', 'szczery', 'mały', 'poprawny', 'idealny', 'atrakcyjny', 'hałaśliwy', 'purpurowy',
         'doskonały', 'podekscytowany', 'sprawiedliwy', 'luźny', 'zagraniczny', 'pikantny', 'świetny', 'niezawodny',
         'śródziemnomorski', 'zimny', 'dziwny', 'bardzo', 'niebieski', 'twardy', 'żółty', 'płytki', 'towarzyski',
         'czerwony', 'prawdopodobny', 'podobny', 'darmowy', 'złamany', 'gruby', 'wygodny', 'tajemniczy', 'przeciętny',
         'zdrowy', 'nieśmiały', 'wściekły', 'legalny', 'zdeterminowany', 'dokładny', 'śliczny', 'wyczerpujący',
         'znakomity', 'malutki', 'szary', 'zakazany', 'natychmiastowy', 'lokalny', 'normalny', 'lepki', 'sławny',
         'obcisły', 'właściwy', 'suchy', 'identyczny', 'rozczarowany', 'okrągły', 'możliwy', 'bolesny', 'niezdrowy',
         'ciemny', 'niezależny', 'zwariowany', 'interesujący', 'bezpieczny', 'brzydki', 'przyjazny', 'pierwszy',
         'istotny', 'olbrzymi', 'smutny', 'kolorowy', 'czysty', 'zły', 'późny', 'słony', 'niedobry', 'narodowy',
         'wspólny', 'inteligentny', 'zaskoczony', 'chudy', 'silny', 'modny', 'poważny', 'długi', 'obrzydliwy', 'drogi',
         'hojny', 'nowy', 'nudny', 'niemożliwy', 'otwarty', 'niemiły', 'średniowieczny', 'stary', 'pyszny', 'brudny',
         'bliski', 'wiarygodny', 'zdolny', 'elektryczny', 'wyjątkowy', 'duży', 'bogaty', 'chory', 'przesądny', 'ważny',
         'wysoki', 'fałszywy', 'skąpy', 'zadowolony', 'wyczerpany', 'głośny', 'trójkątny', 'solidny', 'ostatni',
         'zabawny', 'rzadki', 'cichy', 'odpowiedni', 'uparty', 'trudny', 'nielegalny', 'kwaśny', 'wykończony',
         'paskudny', 'różny', 'szeroki', 'tani', 'spóźniony', 'radosny', 'oczywisty', 'pełny', 'niewłaściwy', 'ciekawy',
         'zazdrosny', 'gorący', 'niezbędny', 'szczególny', 'krótki', 'brązowy', 'nienormalny', 'inny', 'leniwy',
         'przyjemny', 'dostępny', 'ogromny', 'okropny', 'międzynarodowy', 'dobry', 'piękny', 'łatwy', 'biały',
         'prawidłowy', 'cienki', 'prosty', 'miękki', 'caly', 'znudzony', 'popularny', 'pusty', 'nerwowy', 'pechowy',
         'spokojny', 'wąski', 'zamknięty', 'odpowiedzialny', 'obecny', 'niewinny', 'wczesny', 'mokry', 'straszny',
         'szczęśliwy', 'głupi', 'miły', 'ostry', 'śmieszny', 'daleki', 'szybki', 'końcowy', 'obcy', 'biedny',

         'browny',
         'bezwarunkowy',
         'trudny',
         'mierny',
         'znojny',
         'ciemny',
         'zasadniczy',
         'wolny',
         'podstawowy',
         'wrony',
         'mocny',
         'silny',
         'skoczny',
         'potrzebny',
         'poprzedni',

         'nowy',
         'nijaki',
         'sypki',
         'drobnoziarnisty',
         'odporny',
         'mroczny',
         'mały',
         'zbędny',
         'gruby',
         'rzadki',
         'powierzchowny',

'sztuczny', 'różnorodny', 'ścisły', 'niechlujny', 'durny', 'realny', 'tępy', 'mądry', 'niedbały'

         ]
